name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 缓存 target 目录（编译结果）
      - name: Cache Cargo build (target)
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-
          
      - name: Build Debug
        run: RUSTFLAGS="--cfg tokio_unstable" cargo build

      - name: Build Release
        run: RUSTFLAGS="--cfg tokio_unstable" cargo build --release

      - name: Upload a Debug Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: lgs-paintboard-debug
          path: ./target/debug/lgs-paintboard
        
      - name: Upload a Release Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: lgs-paintboard
          path: ./target/release/lgs-paintboard
