name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # 定义操作系统
        build_type: [debug, release]  # 定义构建类型

    runs-on: ${{ matrix.os }}  # 动态选择运行的操作系统
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build ${{ matrix.build_type }} version
        run: cargo build --${{ matrix.build_type }}  # 根据矩阵选择 debug 或 release 构建

      - name: Upload ${{ matrix.build_type }} Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: lgs-paintboard-${{ matrix.os }}-${{ matrix.build_type }}${{ matrix.os == 'windows-latest' && '-exe' || '' }}
          path: ./target/${{ matrix.build_type }}/lgs-paintboard${{ matrix.os == 'windows-latest' && '.exe' || '' }}
